version: '3.2'
services:
  app:
    container_name: chubby-app
    restart: always
    build: .
    ports:
      - 9999:80
    volumes:
      - .:/var/www/html
      # Prevent the vendor directory from being overridden by the volume mount
      - /var/www/html/src/vendor
